[package]
name = "lean_string"
version = "0.1.0"
edition = "2021"
authors = ["ryota2357"]

[dependencies]

[dev-dependencies]
paste = "1.0.15"
proptest = { version = "1.5.0", features = ["attr-macro"] }

[features]
default = []
last_byte = []
