name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format check
        run: cargo fmt --all --check

      - name: Lint check
        run: |
          cargo check --all-features
          cargo clippy --all-features -- -D warnings

  test:
    name: Rust Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        profile: [test, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          cargo test --profile ${{ matrix.profile }}
          cargo test --profile ${{ matrix.profile }} --all-features

      - name: Test (Loom)
        run: RUSTFLAGS="--cfg loom" cargo test --test loom --profile ${{ matrix.profile }} --features loom -- --test-threads=1

      - name: Install Miri
        run: |
          rustup install nightly --profile minimal
          rustup +nightly component add miri

      - name: Test (Miri)
        run: |
          cargo +nightly miri test --profile ${{ matrix.profile }}
          cargo +nightly miri test --profile ${{ matrix.profile }} --all-features
